version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongo-container
    ports:
      - "27017:27017"
  web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes:
        - .:/app
      depends_on:
        - mongodb
volumes:
  data: